#################################################################################
# This file was automatically generated by the Zoundry Raven build script.
# 
#                 --- DO NOT EDIT!! ---
# 
# (to make changes to this class, edit 'version.xsl')
#################################################################################
# Do not alter!  This file is used by Raven to determine the current version of the app.
class ZVersion:
    def __init__(self):
        self.MAJOR_VERSION = 1
        self.MINOR_VERSION = 0
        self.BUILD = 376
        self.MODIFIER = u'' #$NON-NLS-1$
        self.DATE = u'2014-06-21T17:00:56.130Z' #$NON-NLS-1$
    # end __init__()
    def getFullVersionString(self):
        ver = u"%d.%d.%d %s" % (self.MAJOR_VERSION, self.MINOR_VERSION, self.BUILD, self.MODIFIER) #$NON-NLS-1$
        return ver.strip()
    # end getFullVersionString()
    def getBuildDate(self):
        return self.DATE
    # end getBuildDate()
    def getMajorVersion(self):
        return self.MAJOR_VERSION
    # end getMajorVersion()
    def getMinorVersion(self):
        return self.MINOR_VERSION
    # end getMinorVersion()
    def getBuild(self):
        return self.BUILD
    # end getBuild()
# end ZVersion
