// This file declares the IDocHostUIHandler Gateway for Python.
// Generated by makegw.py
// ---------------------------------------------------
//
// Gateway Declaration
#include "mshtmhst.h"
#include "PythonCOM.h"
#include "PythonCOMServer.h"

class PyGDocHostUIHandler : public PyGatewayBase, public IDocHostUIHandler
{
protected:
	PyGDocHostUIHandler(PyObject *instance) : PyGatewayBase(instance) { ; }
	PYGATEWAY_MAKE_SUPPORT2(PyGDocHostUIHandler, IDocHostUIHandler, IID_IDocHostUIHandler, PyGatewayBase)



	// IDocHostUIHandler
	STDMETHOD(ShowContextMenu)(
		DWORD dwID,
		POINT * ppt,
		IUnknown * pcmdtReserved,
		IDispatch * pdispReserved);

	STDMETHOD(GetHostInfo)(
		DOCHOSTUIINFO * pInfo);

	STDMETHOD(ShowUI)(
		DWORD dwID,
		IOleInPlaceActiveObject * pActiveObject,
		IOleCommandTarget * pCommandTarget,
		IOleInPlaceFrame * pFrame,
		IOleInPlaceUIWindow * pDoc);

	STDMETHOD(HideUI)(
		void);

	STDMETHOD(UpdateUI)(
		void);

	STDMETHOD(EnableModeless)(
		BOOL fEnable);

	STDMETHOD(OnDocWindowActivate)(
		BOOL fActivate);

	STDMETHOD(OnFrameWindowActivate)(
		BOOL fActivate);

	STDMETHOD(ResizeBorder)(
		LPCRECT prcBorder,
		IOleInPlaceUIWindow * pUIWindow,
		BOOL fRameWindow);

	STDMETHOD(TranslateAccelerator)(
		LPMSG lpMsg,
		const GUID * pguidCmdGroup,
		DWORD nCmdID);

	STDMETHOD(GetOptionKeyPath)(
		LPOLESTR * pchKey,
		DWORD dw);

	STDMETHOD(GetDropTarget)(
		IDropTarget * pDropTarget,
		IDropTarget ** ppDropTarget);

	STDMETHOD(GetExternal)(
		IDispatch ** ppDispatch);

	STDMETHOD(TranslateUrl)(
		DWORD dwTranslate,
		OLECHAR * pchURLIn,
		OLECHAR ** ppchURLOut);

	STDMETHOD(FilterDataObject)(
		IDataObject * pDO,
		IDataObject ** ppDORet);

};
