<?xml version="1.0" encoding="UTF-8"?>
<xsl:transform
	xmlns:xsl='http://www.w3.org/1999/XSL/Transform'
	version='1.0'>

  <xsl:output method="text" />

  <xsl:template name="outputVersion">
    <xsl:text># This file was automatically generated by the Zoundry Blog Manager build script.</xsl:text>
    <xsl:text>&#x0D;</xsl:text>
    <xsl:text># Do not alter!  This file is used by the Ant script to determine the build version.</xsl:text>
    <xsl:text>&#x0D;</xsl:text>
    <xsl:text>&#x0D;</xsl:text>
    <xsl:text>zoundry.major.version = </xsl:text>
    <xsl:value-of select="/version/major-version" />
    <xsl:text>&#x0D;</xsl:text>
    <xsl:text>zoundry.minor.version = </xsl:text>
    <xsl:value-of select="/version/minor-version" />
    <xsl:text>&#x0D;</xsl:text>
    <xsl:text>zoundry.build.version = </xsl:text>
    <xsl:value-of select="/version/build-version" />
    <xsl:text>&#x0D;</xsl:text>
  </xsl:template>

  <xsl:template match="/">
   	<xsl:call-template name="outputVersion" />
  </xsl:template>

</xsl:transform>
